<?php

// Message Pack for Discuz! Version 1.0.0
// Created by Crossday

$language = array
(

	'title' => '标题',
	'never' => '从未',
	'online' => '在线',
	'onlines' => '人在线',
	'on' => '于',
	'total' => '共',
	'top' => '顶部',
	'admin' => '论坛管理员',
	'supermod' => '超级版主',
	'moderator' => '版主',
	'member' => '会员',
	'guest' => '游客',
	'anonymous' => '匿名',
	'forum' => '论坛',
	'refresh' => '刷 新',
	'show' => '查看',
	'orderby' => '排序方式',
	'submit' => '提 &nbsp; 交',
	'close' => '关 &nbsp; 闭',
	'disable' => '禁用',
	'enable' => '启用',
	'disabled' => '禁用',
	'enabled' => '可用',
	'select' => '选择',
	'reply' => '回复',
	'download' => '下载',
	'forward' => '转发',
	'delete' => '删除',
	'reason' => '理由',
	'advertisement' => '广告',
	'keyword' => '关键字',
	'content' => '内容',
	'time' => '时间',
	'time_now' => '所有时间为 GMT$timenow[offset], 现在时间是 $timenow[time]',
	'visited_forums' => '最近访问的论坛 ...',
	'announcement' => '论坛公告',
	'width' => '宽',
	'height' => '高',
	'edit' => '编辑',

	'online' => '在线',
	'offline' => '离线',
	'action' => '操作',
	'options' => '选项',
	'seccode' => '验证码',
	'seccode_comment' => '请在空白处输入图片中的数字',
	'uid' => 'UID',
	'username' => '用户名',
	'nickname' => '昵称',
	'email' => 'Email',
	'old_password' => '原密码',
	'password' => '密码',
	'password_confirm' => '确认密码',
	'new_password' => '新密码',
	'new_password_confirm' => '确认新密码',
	'gender' => '性别',
	'alipay' => '支付宝账号',
	'homepage' => '主页',
	'location' => '来自',
	'taobao' => '淘宝旺旺',
	'regip' => '注册 IP',
	'lastip' => '上次访问 IP',
	'lastupdate' => '上次更新',
	'regdate' => '注册日期',
	'lastvisit' => '上次访问',
	'credits' => '积分',
	'credits_tax' => '积分交易税',
	'posts' => '帖子',
	'digestposts' => '精华帖',
	'avatar' => '头像',
	'avatarshow' => '天下秀',
	'avatarshow_register' => '注册天下秀',
	'avatarshow_dressup' => '免费换装',
	'avatarshow_bind' => '绑定天下秀',
	'avatarshow_changebind' => '更改绑定',
	'avatarshow_unbind' => '解除绑定',
	'male' => '男',
	'female' => '女',
	'secret' => '保密',
	'birthday' => '生日',
	'status' => '管理头衔',
	'medals' => '勋章',
	'usergroup' => '用户组',
	'extgroups' => '扩展用户组',
	'rank' => '发帖数级别',
	'pm' => '短消息',
	'register' => '注册',
	'register_check_username' => '检查用户名',
	'register_email_comment' => '请确保信箱有效，我们将发送激活说明到这个地址',
	'register_email_censor' => '请不要使用以 $censoremail 结尾的信箱',
	'register_message' => '注册原因',
	'register_from' => '推荐人',
	'register_now' => '立即注册',
	'memberlist' => '会员',
	'login' => '登录',
	'logout' => '退出',
	'search' => '搜索',
	'statistics' => '统计',
	'memcp' => '控制面板',
	'admincp' => '系统设置',
	'faq' => '帮助',
	'style' => '界面风格',
	'tpp' => '每页主题数',
	'ppp' => '每页帖数',
	'timeformat' => '时间格式',
	'dateformat' => '日期格式',
	'timeoffset' => '时差设定',
	'pmsound' => '短消息提示音',
	'custom_status' => '自定义头衔',
	'bio' => '自我介绍',
	'signature' => '个人签名',
	'bytes_limited' => '字节以内',
	'lower_than' => '小于',
	'eg' => '例如',
	'etc' => '等',
	'return' => '返回',
	'goback_home' => '返回',
	'timenow' => '现在时间是',
	'welcometo' => '欢迎光临',
	'your_lastvisit' => '您上次访问是在',
	'use_default' => '- 使用默认 -',
	'please_select' => '- 请选择 -',
	'default' => '默认',
	'customize' => '自定义',
	'or' => '或',
	'to' => '到',
	'from' => '来自',
	'year' => '年',
	'month' => '月',
	'day' => '日',
	'hour' => '小时',
	'hours' => '小时',
	'level' => '级别',
	'none' => '无',
	'all' => '全部',
	'checkall' => '全选',

	'icon' => '图标',
	'author' => '作者',
	'subject' => '标题',
	'description' => '描述',
	'replies' => '回复',
	'views' => '查看',
	'downloads' => '下载次数',
	'dateline' => '发布时间',
	'lastpost' => '最后发表',
	'message' => '内容',
	'message_banned' => '*** 作者被禁止或删除 内容自动屏蔽 ***',
	'poston' => '发表于',

	'attachment' => '附件',
	'attachments' => '附件',
	'attachment_size' => '文件尺寸',
	'attachment_new' => '上传新附件',
	'attachment_allow_exts' => '可用扩展名',

	'send' => '发送',
	'bytes' => '字节',
	'optional' => '可选',
	'clear_cookies' => '清除 Cookies',
	'contactus' => '联系我们',
	'board_allowed' => '系统限制',
	'board_message' => '提示信息',
	'agree' => '同 意',
	'disagree' => '不同意',
	'go_back' => '返回上一页',
	'delete_check' => '删?',
	'add_new' => '新增:',

	'required_info' => '必填内容',
	'optional_info' => '选填内容',
	'board_options' => '论坛个性化设置',
	'other_options' => '其他选项',
	'online_invisible' => '在线列表中隐身',
	'show_email_addr' => 'Email 地址可见',
	'allow_newsletter' => '同意接收论坛通知 (Email 或短消息)',

	'announcements' => '论坛公告',
	'starttime' => '起始时间',
	'endtime' => '结束时间',
	'unlimited' => '不限',

	'rss_subscribe_all' => 'RSS 订阅全部论坛',
	'rss_subscribe_this' => 'RSS 订阅当前论坛',

	'emailfriend' => '推荐给朋友',
	'emailfriend_your_name' => '您的名字',
	'emailfriend_your_email' => '您的 Email',
	'emailfriend_receiver_name' => '接收者名字',
	'emailfriend_receiver_email' => '接收者 Email',
	'emailfriend_message' => '你好！我在 $bbname 看到了这篇帖子，认为很有价值，特推荐给你。{LF}{LF}$thread[subject]{LF}地址 $threadurl{LF}{LF}希望你能喜欢。',

	'forum_modedby' => '版主',
	'forum_category_modedby' => '分类版主',
	'forum_opening' => '*空缺中*',
	'forum_viewall' => '查看全部主题',
	'forum_viewdigest' => '查看本版精华',
	'forum_moderate' => '审核',
	'forum_moderate_threads' => '新主题',
	'forum_moderate_replies' => '新回复',
	'forum_recyclebin' => '回收站',
	'forum_rules' => '本版规则',
	'forum_activeusers' => '正在浏览此论坛的会员',
	'forum_normal_threads' => '论坛主题',
	'forum_nothreads' => '本论坛或指定的范围内尚无主题。',
	'forum_jump' => '论坛跳转 ...',
	'forum_password_require' => '本论坛需要密码，您必须在下面输入正确的密码才能浏览这个论坛。',

	'digest' => '精华区',
	'digest_posts' => '精华',
	'digest_forum' => '以下论坛精华区',

	'threads_all' => '全部主题',
	'last_1_days' => '1 天以来主题',
	'last_2_days' => '2 天以来主题',
	'last_7_days' => '1 周以来主题',
	'last_30_days' => '1 个月以来主题',
	'last_90_days' => '3 个月以来主题',
	'last_180_days' => '6 个月以来主题',
	'last_356_days' => '1 年以来主题',

	'order_lastpost' => '最后回复时间',
	'order_starttime' => '发布时间',
	'order_replies' => '回复数量',
	'order_views' => '浏览次数',
	'order_desc' => '按降序排列',
	'order_asc' => '按升序排列',

	'thread_moved' => '移动',
	'thread_digest' => '精华',
	'thread_sticky' => '置顶',
	'thread_poll' => '投票',
	'thread_keywords' => '相关关键字:',
	'thread_more_related_threads' => '更多相关主题',
	'thread_newposts' => '有新回复',
	'thread_nonewpost' => '无新回复',
	'thread_more_replies' => '多于 $hottopic 篇回复',
	'thread_closed' => '关闭的主题',
	'thread_mod' => '主题管理记录',
	'thread_mod_by' => '本主题由 $lastmod[modusername] 于 $lastmod[moddateline] $lastmod[modaction]',
	'thread_blog' => '本主题被作者加入到他/她的 Blog 中',
	'thread_rate' => '参与评分',
	'thread_printable' => '可打印版本',
	'thread_email_friend' => '推荐给朋友',
	'thread_subscribe' => '订阅主题',
	'thread_favorite' => '收藏主题',
	'thread_print' => '打印本页',

	'thread_moderations' => '主题管理记录',
	'thread_moderations_username' => '操作者',
	'thread_moderations_cron' => '任务系统',
	'thread_moderations_action' => '管理操作',
	'thread_moderations_expiration' => '有效期',
	'thread_moderations_expiration_comment' => '本操作的有效期限，格式为 yyyy-mm-dd，范围 <u>$expirationmin</u> 至 <u>$expirationmax</u>，留空为不限制',
	'thread_moderations_expiration_unlimit' => '永久有效',

	'readperm' => '阅读权限',
	'readperm_thread' => '所需阅读权限',

	'price' => '售价',
	'price_thread' => '浏览需支付',

	'post_subject_toolang' => '您的标题超过 80 个字符的限制。',
	'post_type_isnull' => '请选择主题对应的分类。',
	'post_subject_and_message_isnull' => '请完成标题或内容栏。',
	'post_subject_or_message_isnull' => '请完成标题和内容栏。',
	'post_message_length_invalid' => '您的帖子长度不符合要求。',
	'post_curlength' => '当前长度',
	'post_seccode' => '请输入验证码以便最终发表',
	'post_fastpost' => '快速发新话题',
	'post_fastreply' => '快速回复主题',
	'post_fastreply_author' => '回复 #{$post[number]}{$post[authoras]} 的帖子',
	'post_readperm_comment' => '0 为不限制',
	'post_price_refunded' => '本主题被强制退款',
	'post_price_free' => '本主题自发表起已超过最长出售时限',
	'post_price_comment' => '最高 $maxprice {$extcredits[$creditstrans][unit]}',
	'post_price_income_comment' => '，单一主题作者最高收入 $maxincperthread {$extcredits[$creditstrans][unit]}',
	'post_price_charge_comment' => '，最高出售时限 $maxchargespan 小时',
	'post_price_free_comment' => '您可以使用 <b>[free]</b>message<b>[/free]</b> 代码发表无需付费也能查看的免费信息',
	'post_parseurl' => 'URL 识别',
	'post_html' => 'Html 代码',
	'post_anonymous' => '使用匿名发帖',
	'post_smilies' => 'Smilies',
	'post_smilies_more' => '更多 Smilies',
	'post_discuzcode' => 'Discuz! 代码',
	'post_discuzcode_normal_mode' => '提示插入',
	'post_discuzcode_normal_mode_comment' => '点击代码按钮后出现向导窗口帮助您完成代码插入',
	'post_discuzcode_help_mode' => '帮助信息',
	'post_discuzcode_help_mode_comment' => '点击相应的代码按钮即可获得相应的说明和提示',
	'post_discuzcode_adv_mode' => '直接插入',
	'post_discuzcode_adv_mode_comment' => '点击代码按钮后不出现提示即直接插入相应代码',
	'post_discuzcode_extra_font' => '<option value="宋体">宋体</option><option value="黑体">黑体</option>',
	'post_discuzcode_fontsize' => '设置字号',
	'post_discuzcode_fontsize_comment' => '将标签所包围的文字设置成指定字号。\n例如：[size=3]文字大小为 3[/size]',
	'post_discuzcode_fontsize_normal' => '请输入要设置为指定字号的文字。',
	'post_discuzcode_font' => '设定字体',
	'post_discuzcode_font_comment' => '将标签所包围的文字设置成指定字体。\n例如：[font=仿宋]字体为仿宋[/font]',
	'post_discuzcode_font_normal' => '请输入要设置成指定字体的文字。',
	'post_discuzcode_color' => '定义文本颜色',
	'post_discuzcode_color_comment' => '将标签所包围的文本变为制定颜色。\n例如：[color=red]红颜色[/color]',
	'post_discuzcode_color_normal' => '请输入要设置成指定颜色的文字。',
	'post_discuzcode_bold' => '插入粗体文本',
	'post_discuzcode_bold_comment' => '将标签所包围的文本变成粗体。\n例如：[b]粗体文字[/b]',
	'post_discuzcode_bold_normal' => '请输入要设置成粗体的文字。',
	'post_discuzcode_italicize' => '插入斜体文本',
	'post_discuzcode_italicize_comment' => '将标签所包围的文本变成斜体。\n例如：[i]斜体文字[/i]',
	'post_discuzcode_italicize_normal' => '请输入要设置成斜体的文字。',
	'post_discuzcode_underline' => '插入下划线',
	'post_discuzcode_underline_comment' => '给标签所包围的文本加上下划线。\n例如：[u]下划线文字[/u]',
	'post_discuzcode_underline_normal' => '请输入要加下划线的文字。',
	'post_discuzcode_center' => '居中对齐',
	'post_discuzcode_center_comment' => '将标签所包围的文本居中对齐显示。\n例如：[align=center]内容居中[/align]',
	'post_discuzcode_center_normal' => '请输入要居中对齐的文字。',
	'post_discuzcode_hyperlink' => '插入超级链接',
	'post_discuzcode_hyperlink_comment' => '插入一个超级连接。\n例如：\n[url]http://www.mydomain.com[/url]\n[url=http://www.mydomain.com]我的网站[/url]',
	'post_discuzcode_hyperlink_normal' => '请输入链接显示的文字，如果留空则直接显示链接。',
	'post_discuzcode_hyperlink_normal_input' => '请输入 URL。',
	'post_discuzcode_email' => '插入邮件地址',
	'post_discuzcode_email_comment' => '插入邮件地址连接。\n例如：\n[email]myname@mydomain.com[/email]\n[email=myname@mydomain.com]我的名字[/email]',
	'post_discuzcode_email_normal' => '请输入链接显示的文字，如果留空则直接显示邮件地址。',
	'post_discuzcode_email_normal_input' => '请输入邮件地址。',
	'post_discuzcode_image' => '插入图像',
	'post_discuzcode_image_comment' => '在文本中插入一幅图像。\n例如：[img]{$boardurl}images/logo.gif[/img]',
	'post_discuzcode_image_normal' => '请输入图像的 URL。',
	'post_discuzcode_flash' => '插入 flash',
	'post_discuzcode_flash_comment' => '在文本中插入 flash 动画。\n例如：[swf]{$boardurl}images/banner.swf[/swf]',
	'post_discuzcode_flash_normal' => '请输入 flash 动画的 URL。',
	'post_discuzcode_code' => '插入代码',
	'post_discuzcode_code_comment' => '插入程序或脚本原始代码。\n例如：[code]echo \"这里是我们的论坛\";[/code]',
	'post_discuzcode_code_normal' => '请输入要插入的代码。',
	'post_discuzcode_quote' => '插入引用',
	'post_discuzcode_quote_comment' => '将标签所包围的文本作为引用特殊显示。\n例如：[quote]Discuz! 是由北京康盛世纪科技有限公司开发的论坛软件[/quote]',
	'post_discuzcode_quote_normal' => '请输入要作为引用显示的文字。',
	'post_discuzcode_list' => '插入列表',
	'post_discuzcode_list_comment' => '插入可由浏览器显示来的规则列表项。\n例如：\n[list]\n[*]；列表项 #1\n[*]；列表项 #2\n[*]；列表项 #3\n[/list]',
	'post_discuzcode_list_normal' => '请选择列表格式(可选字段)：字母式列表输入 \"A\"；数字式列表输入 \"1\"。',
	'post_discuzcode_list_normal_error' => '错误：列表格式只能选择输入 \\"A\\" 或 \\"1\\"。',
	'post_discuzcode_list_normal_input' => '请输入列表项目内容，如果留空表示项目结束。',
	'post_discuzcode_alipay' => '插入支付宝交易代码',
	'post_discuzcode_alipay_normal_account' => '请输入您的支付宝帐户(必填字段)，如果没有，请输入您长期有效的 Email 地址。',
	'post_discuzcode_alipay_normal_account_error' => '错误：您必须输入支付宝账户或有效的 Email 地址。',
	'post_discuzcode_alipay_normal_merchandise' => '请输入商品名称(可选字段)，长度不要超过 30 个汉字。',
	'post_discuzcode_alipay_normal_price' => '请输入商品价格(可选字段)。',
	'post_discuzcode_alipay_normal_description' => '请输入商品说明(可选字段)，长度不要超过 200 个汉字。',
	'post_discuzcode_alipay_normal_homepage' => '请输入商品展示网址(可选字段)，例如 http://www.discuz.com/software.htm',
	'post_discuzcode_alipay_normal_type' => '请输入交易类型(可选字段)：商品购买输入 \\"1\\"；服务购买输入 \\"2\\"；网络拍卖输入 \\"3\\"；捐赠输入 \\"4\\"。',
	'post_discuzcode_alipay_normal_transport' => '请输入发货方式(可选字段)：平邮输入 \\"1\\"；快递输入 \\"2\\"；虚拟物品输入 \\"3\\"。',
	'post_discuzcode_insert_font' => '- 字体 -',
	'post_discuzcode_insert_size' => '- 字号 -',
	'post_discuzcode_insert_color' => '- 颜色 -',
	'post_attachment_insert' => '点击这里将本附件插入帖子内容中当前光标的位置',
	'post_attachment_comment' => '<span class="bold">技巧提示:</span> 您可以在帖子中使用 [attach]aid[/attach] 标签将附件显示于帖子内容的指定位置，而不按照默认方式排列在内容的尾部。点击 aid 数字可以在当前光标位置自动插入此代码。',
	'post_imgcode' => '[img] 代码',
	'post_show_sig' => '使用个人签名',
	'post_email_notify' => '接收新回复邮件通知',
	'post_topicsubmit' => '发表帖子',
	'post_previewpost' => '预览帖子',
	'post_topicreset' => '清空内容',
	'post_thread_review' => '主题回顾',
	'post_replies_toolong' => '本主题回复较多，请 <a href="viewthread.php?fid=$fid&tid=$tid">点击这里</a> 查看。',
	'post_submit_hotkey' => '[完成后可按 Ctrl+Enter 发布]',
	'post_newthread' => '发新话题',
	'post_newreply' => '发表回复',
	'post_editpost' => '编辑帖子',
	'post_poll_options' => '投票选项',
	'post_poll_comment' => '每一行为一个选项<br>最大选项数:',
	'post_poll_allowmultiple' => '多选投票',
	'post_trade_seller' => '我的支付宝账户',
	'post_trade_name' => '商品名称',
	'post_trade_price' => '商品价格',
	'post_trade_quality' => '商品成色',
	'post_trade_locus' => '商品所在地',
	'post_trade_transport' => '物流方式',
	'post_trade_transport_seller' => '卖家承担邮费',
	'post_trade_transport_buyer' => '买家承担邮费',
	'post_trade_transport_comment' => '通过邮费承担方选择注明该交易是由买卖哪方承担运费。<br>如果是买家承担运费，请选择可以提供的物流方式以及相应费用。',
	'post_trade_transport_mail' => '平邮',
	'post_trade_transport_mail_unit' => '元 (不填视作不提供平邮)',
	'post_trade_transport_express' => '快递',
	'post_trade_transport_express_unit' => '元 (不填视作不提供快递)',
	'post_trade_transport_virtual' => '虚拟物品或无需邮递',
	'post_trade_description' => '商品描述',

	'post_check_length' => '字数检查',
	'post_delpost' => '!删除本帖',
	'post_stick_thread' => '主题置顶',
	'post_digest_thread' => '精华帖子',
	'post_blog_thread' => '加入 Blog',

	'getpassword' => '重置密码',
	'lostpassword' => '忘记密码',

	'index_status' => '头衔',
	'index_threads' => '篇主题',
	'index_posts' => '篇帖子',
	'index_today' => '今日',
	'index_activeusers' => '在线用户',
	'index_members' => '位会员',
	'index_invisibles' => '隐身',
	'index_guests' => '位游客',
	'index_mostonlines' => '最高纪录是',
	'index_users' => '人',
	'show_newthreads' => '查看新帖',
	'show_mytopics' => '我的话题',
	'mark_read' => '标记已读',
	'welcome_newmember' => '欢迎新会员',
	'index_announcements' => '公告',
	'index_noannouncement' => '到目前为止没有论坛公告。',
	'forum_name' => '论坛',
	'forum_threads' => '主题',
	'forum_posts' => '帖数',
	'forum_todayposts' => '今日',
	'forum_lastpost' => '最后发表',
	'forum_lastpost_in' => '标题',
	'forum_lastpost_by' => 'by',
	'forum_moderators' => '版主',
	'forum_newposts' => '有新帖的论坛',
	'forum_nonewpost' => '无新帖的论坛',
	'forum_subforums' => '子论坛',
	'board_links' => '联盟论坛',
	'todays_birthdays' => '今日生日',
	'todays_birthdays_none' => '今天没有过生日的用户',
	'private_forum' => '私密论坛',

	'member_login' => '会员登录',
	'member_logout' => '退出登录',

	'credits_policy' => '积分策略说明',
	'credits_policy_view' => '查看积分策略说明',
	'credits_policy_post' => '发新主题',
	'credits_policy_forum_post' => '本版发新主题',
	'credits_policy_reply' => '发表回复',
	'credits_policy_forum_reply' => '本版发表回复',
	'credits_policy_digest' => '加入精华',
	'credits_policy_postattach' => '发表附件',
	'credits_policy_getattach' => '下载附件',
	'credits_policy_pm' => '发短消息',
	'credits_policy_search' => '搜索',
	'credits_policy_promotion_visit' => '访问推广',
	'credits_policy_promotion_register' => '注册推广',
	'credits_policy_lowerlimit' => '积分下限',
	'credits_policy_lowerlimit_comment' => '当您该项积分低于此下限设置的数值时，将无法执行积分策略中涉及扣减此项积分的操作',
	'credits_policy_formula' => '总积分计算公式',

	'login_permanent' => '永久',
	'login_one_month' => '一个月',
	'login_one_day' => '一天',
	'login_one_hour' => '一小时',
	'login_this_task' => '浏览器进程',
	'login_related_faq' => '相关帮助',
	'login_invisible' => '隐身登录',
	'login_normal_mode' => '正常模式',
	'login_invisible_mode' => '隐身模式',
	'login_cookie_time' => 'Cookie 有效期',
	'login_secques' => '您设置了安全提问，请输入正确的提问和回答后才能登录。',
	'login_secques_comment' => '如果您设置了安全提问，请在此输入正确的问题和回答',
	'login_timeoffset' => '注意:\n\n您本地计算机的时间设定与论坛时间相差超过 24 个小时，\n这可能会影响您的正常登录，请调整本地计算机设置。\n\n当前论坛时间是: $thetimenow\n如果您认为论坛时间不准确，请与论坛管理员联系。',

	'security_question' => '安全提问',
	'security_answer' => '回答',
	'security_question_0' => '无安全提问',
	'security_question_1' => '母亲的名字',
	'security_question_2' => '爷爷的名字',
	'security_question_3' => '父亲出生的城市',
	'security_question_4' => '您其中一位老师的名字',
	'security_question_5' => '您个人计算机的型号',
	'security_question_6' => '您最喜欢的餐馆名称',
	'security_question_7' => '驾驶执照的最后四位数字',

	'member_list' => '会员列表',

	'group_expiry' => '用户组有效期',
	'group_expiry_time' => '到期时间',
	'group_expiry_type' => '类型',
	'group_expiry_type_main' => '主用户组',
	'group_expiry_type_ext' => '扩展用户组',
	'group_expiry_comment' => '<ul><li>此处仅列出具有有效期限制的用户组列表，详细的用户组归属关系请到控制面板的“公众用户组”中设定和查看。<li>如果用户组名称被删除线覆盖，说明此用户组已经过期，即日起您将不拥有该组的任何权限。',

	'memcp_welcome' => '您好 $discuz_userss ，欢迎进入控制面板，这里提供相关的资料设定与论坛快捷功能等。',
	'memcp_home' => '控制面板首页',
	'memcp_info' => '帐号信息',
	'memcp_email_reverify' => '重新验证 Email 有效性',
	'memcp_validating' => '账户审核',
	'memcp_validating_info' => '管理员设置了新注册用户需要人工验证，您的帐号已提交过 <span class="bold">$validating[submittimes]</span> 次验证请求，目前尚未通过验证。',
	'memcp_validating_status' => '当前状态',
	'memcp_validating_status_0' => '等待管理人员进行审核',
	'memcp_validating_status_1' => '审核被拒绝，您可以修改注册原因后再次提交',
	'memcp_validating_admin' => '审核管理员',
	'memcp_validating_time' => '审核时间',
	'memcp_validating_remark' => '管理员给您的留言',
	'memcp_buddylist' => '好友列表',
	'memcp_buddylist_note' => '备注',
	'memcp_buddylist_time' => '加入时间',
	'memcp_buddylist_add' => '添加',
	'memcp_buddylist_edit' => '编辑好友列表',
	'memcp_buddylist_remove' => '删除该好友',
	'memcp_last_5_pm' => '最近的五条短消息',
	'memcp_nopm' => '目前收件箱中没有消息。',
	'memcp_last_5_subs' => '最近被回复的五个订阅主题',
	'memcp_nosubs' => '目前没有被订阅的主题。',
	'memcp_nofavs' => '目前没有被收藏的主题。',
	'memcp_avatar_list' => '论坛头像列表',
	'memcp_profile' => '编辑个人资料',
	'memcp_profile_old_passwd_comment' => '如不需要更改密码或安全提问，此处请留空',
	'memcp_profile_passwd_comment' => '如不需要更改密码，此处请留空',
	'memcp_profile_email_comment' => '!如更改地址，系统将修改您的密码并重新验证其有效性，请慎用',
	'memcp_profile_security_keep' => '保持原有的安全提问和答案',
	'memcp_profile_security_comment' => '如果您启用安全提问，登录时需填入相应的项目才能登录',
	'memcp_profile_security_answer_comment' => '如您设置新的安全提问，请在此输入答案',
	'memcp_profile_unchangeable_comment' => '请认真填写本项目，一旦确定将不可修改',
	'memcp_profile_avatarshow_comment' => '如果您还没有注册天下秀形象，请点击形象下的“注册天下秀”进行注册，更换喜欢的着装并保存形象，然后在论坛中绑定您的天下秀账号，您还可以同时在其他 Discuz! 论坛系统中绑定同一个天下秀账号，您的形象将直接在论坛中显示出来',
	'memcp_profile_avatarshow_confirm' => '解除天下秀绑定后您的形象将不能在论坛中显示，您确定要解除绑定吗?',
	'memcp_credits' => '积分交易',
	'memcp_credits_caculate' => '计 &nbsp; 算',
	'memcp_credits_confirm' => '积分操作不能恢复，您确认吗?',
	'memcp_credits_min_balance' => '交易后最低余额',
	'memcp_credits_transfer' => '积分转账',
	'memcp_credits_transfer_message' => '附言',
	'memcp_credits_transfer_message_comment' => '如果输入附言，系统将自动向接收者发送短消息通知',
	'memcp_credits_transfer_comment' => '<ul><li>积分转账可以根据论坛管理员设置的交易积分，将您的积分转让给其他用户。<li>接收者收到积分的实际数值，是被扣除交易税后计算出来的，即只要进行积分交易，就可能会产生交易损失。<li>积分交易一旦提交不可恢复，请确定无误后再进行操作。',
	'memcp_credits_transfer_caculate' => '接收者的所得为',
	'memcp_credits_transfer_send' => '积分转出',
	'memcp_credits_transfer_receive' => '积分转入',
	'memcp_credits_transfer_bank' => '银行现金转入',
	'memcp_credits_exchange' => '积分兑换',
	'memcp_credits_exchange_amount' => '积分数量',
	'memcp_credits_exchange_source' => '原积分',
	'memcp_credits_exchange_target' => '目标积分',
	'memcp_credits_exchange_ratio' => '兑换比率',
	'memcp_credits_exchange_comment' => '<ul><li>积分兑换是根据论坛管理员设置的可兑换积分，将您自己的某种积分，兑换成另外一种积分。<li>兑换比率为该项积分对应一个单位标准积分的值。例如兑换比率为 2 的积分 1 分，相当于兑换比率为 1 的积分 2 分，即兑换比率越大，该项积分越有价值。<li>兑换成目标积分的实际数值，是按照兑换比率折算的目标积分，并扣除交易税后计算出来的，即只要进行积分交易，就可能会产生交易损失。<li>积分交易一旦提交不可恢复，请确定无误后再进行操作。',
	'memcp_credits_exchange_caculate' => '兑换后所得目标积分为',
	'memcp_credits_addfunds' => '积分充值',
	'memcp_credits_addfunds_rules' => '充值规则',
	'memcp_credits_addfunds_rules_ratio' => '人民币现金 <b>1</b> 元',
	'memcp_credits_addfunds_rules_min' => '单次最低充值',
	'memcp_credits_addfunds_rules_max' => '单次最高充值',
	'memcp_credits_addfunds_rules_month' => '最近 30 天最高充值',
	'memcp_credits_addfunds_comment' => '您可以以人民币现金在线支付的形式，为您的交易积分账户充值用于购买帖子、用户组权限或其他虚拟消费活动。<li>积分充值不能撤销或退款，因此请您在充值前确定是否需要，及仔细核对充值的金额。<li><b>您成功支付后有系统可能需要几分钟的时间等待支付结果，因此可能无法瞬间入账，请注意查收系统发送的短消息。如果超过 48 小时仍未收到通知短消息，请与论坛管理员联系。</b>',
	'memcp_credits_addfunds_amount' => '账户充值数额',
	'memcp_credits_addfunds_caculate' => '您需要在线支付的人民币(元)金额为',
	'memcp_credits_log' => '积分记录',
	'memcp_credits_log_transaction' => '转账与兑换记录',
	'memcp_credits_log_transaction_fromto' => '来自/到',
	'memcp_credits_log_transaction_outgo' => '支出',
	'memcp_credits_log_transaction_income' => '收入',
	'memcp_credits_log_payment' => '主题付费记录',
	'memcp_credits_log_payment_dateline' => '付费时间',
	'memcp_credits_log_payment_refunded' => '已退款',
	'memcp_credits_log_income' => '主题收益记录',
	'memcp_credits_log_income_buyer' => '购买者',
	'memcp_credits_log_none' => '目前没有积分交易记录。',
	'memcp_credits_info' => '积分概况',
	'memcp_usergroups' => '公众用户组',
	'memcp_usergroups_charged' => '公众用户组收费',
	'memcp_usergroups_title' => '用户组头衔',
	'memcp_usergroups_dailyprice' => '日价格',
	'memcp_usergroups_minspan' => '最短购买时间',
	'memcp_usergroups_expiry' => '到期时间',
	'memcp_usergroups_join' => '加入',
	'memcp_usergroups_join_ext' => '扩展用户组',
	'memcp_usergroups_join_main' => '主用户组',
	'memcp_usergroups_join_comment' => '您至少需要支付{$extcredits[$creditstrans][title]} $group[minamount] {$extcredits[$creditstrans][unit]}以获取 $group[minspan] 天的本用户组权限，不设上限。购买后不能退款，请付费前仔细确定是否加入本组。',
	'memcp_usergroups_exit' => '退出',
	'memcp_usergroups_exit_comment' => '本操作不可恢复，您退出收费公众用户组后，如需再次加入，将重新支付相应的费用，因此请在提交前仔细确定是否退出本组。',
	'memcp_usergroups_comment' => '<ul><li><b><i>粗斜体显示的用户组</i></b>为您已经加入，但并非公众类型的用户组，如果退出，将无法再加入该组，而只能由管理员通过系统设置修改。<li><u>下划线显示的用户组</u>不具有切换用户组的权限，因此您一旦设置其为主用户组，将失去加入或离开公众用户组的权限，请务必慎用！<li>日价格为 0 的用户组为免费公众用户组，您可以自由加入或退出；日价格高于 0 的用户组为收费公众用户组，您需要支付相应的交易积分才能加入。<li>加入收费公众用户组的最低花费为：日价格*最短购买时间。如果您希望将收费公众用户组设置为主用户组，请先将该收费用户组加为扩展用户组，之后再设置成为主用户组。',
	'memcp_usergroups_days' => '天',
	'memcp_usergroups_span' => '购买时间',

	'memcp_nogroups' => '目前没有可加入的公众用户组。',
	'memcp_subscriptions' => '订阅列表',
	'memcp_favorites' => '收藏夹',
	'memcp_rate_log' => '评分记录',

	'reportpost' => '报告帖子',
	'reportpost_to' => '报告给',
	'reportpost_suggestion' => '我的意见',
	'reportpost_reason' => '我对这个帖子有异议，特向您报告',

	'search_keywords' => '关键字',
	'search_keywords_comment' => '关键字中可使用通配符 "*"<br><br>匹配多个关键字全部，可用空格或 "AND" 连接。如 win32 AND unix<br>匹配多个关键字其中部分，可用 "|" 或 "OR" 连接。如 win32 OR unix',
	'search_username_comment' => '用户名中可使用通配符 "*"，如 *user*',
	'search_range' => '搜索范围',
	'search_orderby' => '排序类型',
	'search_all_forums' => '搜索所有开放的论坛',
	'search_qihoo' => '奇虎全文',
	'search_title' => '标题搜索',
	'search_fulltext' => '全文搜索',
	'search_blog' => '搜索 Blog',
	'search_any_date' => '全部时间',
	'1_days_ago' => '1 天前',
	'2_days_ago' => '2 天前',
	'7_days_ago' => '1 周前',
	'30_days_ago' => '1 个月前',
	'90_days_ago' => '3 个月前',
	'180_days_ago' => '6 个月前',
	'356_days_ago' => '1 年前',
	'search_newer' => '之后',
	'search_older' => '之前',
	'search_nomatch' => '对不起，没有找到匹配结果。',

	'qihoo_hot_searches' => '热门搜索',
	'qihoo_topics' => '论坛专题',
	'qihoo_custom_topics' => '用户专题',
	'qihoo_keyword' => '输入关键词，快速搜索本论坛',
	'qihoo_search_filltext' => '全文',
	'qihoo_search_title' => '标题',
	'qihoo_search' => '搜帖',
	'qihoo_relatedthreads' => '相关主题',
	'qihoo_topic_powered_by' => '本功能由奇虎提供',
	'qihoo_topic_nothreads' => '目前没有与专题相关的帖子。',

	'message_forward' => '如果您的浏览器没有自动跳转，请点击这里',
	'message_go_back' => '[ 点击这里返回上一页 ]',

	'stats' => '论坛统计',
	'stats_rank' => '排行榜',
	'stats_main' => '基本概况',
	'stats_views' => '流量统计',
	'stats_week' => '星期流量',
	'stats_hour' => '时段流量',
	'stats_agent' => '客户软件',
	'stats_posthist' => '发帖量记录',
	'stats_forums_rank' => '论坛排行',
	'stats_threads_rank' => '主题排行',
	'stats_posts_rank' => '发帖排行',
	'stats_credits_rank' => '积分排行',
	'stats_onlinetime' => '在线时间',
	'stats_team' => '管理团队',
	'stats_modworks' => '管理统计',
	'stats_main_member' => '会员统计',
	'stats_main_board' => '论坛统计',
	'stats_main_members' => '注册会员',
	'stats_main_admins' => '管理成员',
	'stats_main_new' => '新会员',
	'stats_main_topposter' => '今日论坛之星',
	'stats_main_total_posted' => '发帖数',
	'stats_main_posters' => '发帖会员',
	'stats_main_nonposters' => '未发帖会员',
	'stats_main_posters_percent' => '发帖会员占总数',
	'stats_main_posts_avg' => '平均每人发帖数',
	'stats_main_members_count' => '会员数',
	'stats_main_forums_count' => '论坛数',
	'stats_main_threads_count' => '主题数',
	'stats_main_posts_count' => '帖子数',
	'stats_main_rpt' => '平均每个主题被回复次数',
	'stats_main_nppd' => '平均每日新增帖子数',
	'stats_main_todays_newposts' => '最近 24 小时新增帖子数',
	'stats_main_hot_forum' => '最热门的论坛',
	'stats_main_board_activity' => '论坛活跃指数',
	'stats_main_pageview' => '流量概况',
	'stats_main_total_pageview' => '总页面流量',
	'stats_main_person_time' => '人次',
	'stats_main_total_visitors' => '共计来访',
	'stats_main_pv_avg' => '平均每人浏览',
	'stats_main_maxpv_month' => '被访问最多的月份: <span class="bold">$maxmonth_year</span> 年 <span class="bold">$maxmonth_month</span> 月',
	'stats_main_period_of_time' => '时段',
	'stats_main_month' => '月份流量',
	'stats_topics' => '主题',
	'stats_posts' => '发帖',
	'stats_digest_posts' => '精华帖',
	'stats_posts_thismonth' => '最近 30 天发帖',
	'stats_posts_today' => '最近 24 小时发帖',
	'stats_os' => '操作系统',
	'stats_browser' => '浏览器',
	'stats_month_posts' => '每月新增帖子记录',
	'stats_day_posts' => '每日新增帖子记录',
	'stats_threads_most_views' => '被浏览最多的主题',
	'stats_threads_most_replies' => '被回复最多的主题',
	'stats_onlinetime_total' => '总在线时间排行(小时)',
	'stats_onlinetime_thismonth' => '本月在线时间排行(小时)',
	'stats_team_admins' => '管理员和超级版主',
	'stats_team_offdays' => '离开天数',
	'stats_modworks_month' => '月份',
	'stats_modworks_thismonth' => '本月管理',
	'stats_modworks_all' => '全体管理人员',
	'stats_modworks_details' => '查看详细管理统计',
	'stats_update' => '统计数据已被缓存，上次于 $lastupdate 被更新，下次将于 $nextupdate 进行更新',

	'admin_modoptions' => '管理选项',
	'admin_moderate' => '批量管理选项',
	'admin_reason' => '操作原因',
	'admin_reason_required' => '您必须输入理由才能进行操作',
	'admin_reason_custom' => '请在这里输入您的理由',
	'admin_pm' => '发短消息通知作者',
	'admin_next' => '后续操作',

	'admin_bump' => '提升主题',
	'admin_stick' => '主题置顶',
	'admin_unstick' => '解除置顶',
	'admin_stick_unstick' => '置顶/解除置顶',
	'admin_split' => '分割主题',
	'admin_split_newsubject' => '新主题的标题',
	'admin_open' => '打开主题',
	'admin_close' => '关闭主题',
	'admin_repair' => '修复主题',
	'admin_openclose' => '关闭/打开主题',
	'admin_move' => '移动主题',
	'admin_type' => '主题分类',
	'admin_highlight' => '高亮显示',
	'admin_move_target' => '目标论坛/分类',
	'admin_move_type' => '移动方式',
	'admin_move_redirect' => '移动主题并在原来的论坛中保留转向',
	'admin_merge' => '合并主题',
	'admin_merge_tid' => '主题 tid',
	'admin_merge_tid_comment' => '即将与这个主题合并的 tid，如 viewthread.php?tid=48，tid 为 48',
	'admin_getip' => '查看 IP',
	'admin_getip_this' => '此用户的 IP 地址是',
	'admin_ban_this_ip' => '禁止此 IP',
	'admin_highlight_style' => '字体样式',
	'admin_highlight_color' => '字体颜色',
	'admin_highlight_bold' => '粗体',
	'admin_highlight_italic' => '斜体',
	'admin_highlight_underline' => '下划线',
	'admin_digest' => '设置精华',
	'admin_digest_add' => '加入精华',
	'admin_digest_remove' => '解除精华',
	'admin_digest_addremove' => '加入/解除精华',
	'admin_delposts' => '删除选定帖子',
	'admin_delthread' => '删除主题',
	'admin_delete_keep_author_credits' => '不减主题作者积分',
	'admin_delete_keep_replier_credits' => '不减回复者积分',
	'admin_delpost' => '删除回帖',
	'admin_refund' => '强制退款',

	'whosonline' => '在线用户',
	'online_only_guests' => '当前只有游客或隐身会员在线',
	'online_action' => '当前动作',
	'online_in_forum' => '所在论坛',
	'online_in_thread' => '所在主题',
	'online_ip' => 'IP 地址',

	'post_percent' => '占全部帖子的',
	'posts_per_day' => '平均每日发帖',
	'personal_info' => '个人信息',
	'somebodys_profile' => '$member[username] 的个人资料',
	'add_to_buddylist' => '加为好友',
	'search_posts' => '搜索帖子',
	'edit_member' => '编辑用户',
	'moderations' => '工作统计',
	'valid_before' => '有效期至',
	'pageviews' => '页面访问量',
	'onlinetime' => '在线时间',
	'onlinetime_upgrade' => '升级剩余时间 <span class="bold">$member[olupgrade]</span> 小时',
	'onlinetime_total' => '总计在线',
	'onlinetime_thismonth' => '本月在线',

	'poll_subject' => '投票标题',
	'poll_multiple' => '多选',
	'poll_single' => '单选',
	'poll_view_voters' => '[参与投票的会员]',
	'poll_voters' => '参与投票的会员',

	'last_thread' => '上一主题',
	'next_thread' => '下一主题',
	'disable_highlight' => '取消高亮',
	'unregistered' => '未注册',
	'member_deleted' => '该用户已被删除',
	'member_anonymous' => '该用户匿名发贴',
	'regtime' => '注册',
	'online_status' => '状态',
	'payto_author' => '用支付宝求购',
	'attach_nopermission' => '您所在的用户组无法下载或查看附件',
	'attach_download_count' => '该附件被下载次数',
	'attach_img' => '图片附件',
	'image_open_zoom' => '点击在新窗口查看全图\\nCTRL+鼠标滚轮放大或缩小',

	'view_profile' => '查看资料',
	'visit_home' => '访问主页',
	'send_pm' => '发短消息',
	'edit_post' => '编辑帖子',
	'reply_quote' => '引用回复',
	'report_to_moderator' => '向版主反映这个帖子',

	'rate' => '评分',
	'rate_quota_today' => '今日还能评分 $maxratetoday[$id] {$extcredits[$id][unit]}',
	'rate_this_post' => '给本帖评分',
	'rate_view' => '查看评分记录',
	'rate_view_post' => '原帖内容',

	'pay' => '购买主题',
	'pay_comment' => '本主题需向作者支付相应积分才能浏览，您可根据作者信誉、出售价格及已购买用户的评价确定购买与否。',
	'pay_buyers' => '已购买人数',
	'pay_author_income' => '作者所得',
	'pay_balance' => '购买后余额',
	'pay_max_income' => '作者最高收入',
	'pay_free_time' => '强制免费期限',
	'pay_free_message' => '免费信息',
	'pay_replies' => '最新若干回复',
	'pay_view' => '查看付款记录',
	'pay_nobuyers' => '目前没有用户购买此主题。',
	'pay_noreplies' => '目前尚无回复。',

	'week_sun' => '日',
	'week_mon' => '一',
	'week_tues' => '二',
	'week_wed' => '三',
	'week_thurs' => '四',
	'week_fri' => '五',
	'week_sat' => '六',

	'blog' => 'Blog',
	'blog_new' => '发表 Blog',
	'blog_add' => '加入 Blog',
	'blog_remove' => '移除 Blog',
	'blog_add_remove' => '加入/移除 Blog 文章',
	'blog_search' => '搜索 Blog 文章',
	'blog_category' => '栏目',
	'blog_home' => 'Blog 首页',
	'blog_comments' => '评论',
	'blog_categories' => '栏目分类',
	'blog_hot' => '最热的 5 篇文章',
	'blog_post_comment' => '发表评论',
	'blog_nonexistence' => '指定的时间范围内没有 Blog 文章。',
	'blog_closed' => '本文章已关闭或您没有权限发表评论。',

	'pm_new' => '您有 $newpmnum 条新消息',
	'pm_new_detail' => '[查看详情]',
	'pm_new_ignore' => '[不再提示]',

	'pm_folders' => '文件夹',
	'pm_shortcut' => '快捷方式',
	'pm_send' => '发送短消息',
	'pm_send_save_outbox' => '保存到发件箱中 &nbsp; [完成后可按 Ctrl+Enter 发布]',
	'pm_search' => '搜索短消息',
	'pm_search_username' => '发信人或收信人',
	'pm_search_username_comment' => '发信人或收信人用户名中可使用通配符 "*"，如 *user*',
	'pm_search_read' => '已读短消息',
	'pm_search_unread' => '未读短消息',
	'pm_search_orderby_dateline' => '按收发时间',
	'pm_search_orderby_from' => '按收发信人名',
	'pm_inbox' => '收件箱',
	'pm_outbox' => '发件箱',
	'pm_track' => '消息跟踪',
	'pm_data_usage' => '空间使用',
	'pm_total' => '共有短消息',
	'pm_storage' => '短消息上限',
	'pm_orig_message' => '原始短消息',
	'pm_to_buddy' => '好友群发',
	'pm_archive' => '导出短消息',
	'pm_archive_delete' => '导出后删除短消息',
	'pm_archive_folder' => '文件夹',
	'pm_archive_from' => '时间范围',
	'pm_archive_from_1_days' => '1 天',
	'pm_archive_from_2_days' => '2 天',
	'pm_archive_from_7_days' => '1 周',
	'pm_archive_from_30_days' => '1 个月',
	'pm_archive_from_90_days' => '3 个月',
	'pm_archive_from_180_days' => '6 个月',
	'pm_archive_from_365_days' => '1 年',
	'pm_archive_from_newer' => '以来',
	'pm_archive_from_older' => '以前',
	'pm_archive_amount' => '导出短消息数量',
	'pm_ignore' => '忽略列表',
	'pm_ignore_comment' => '添加多个忽略人员名单时用逗号 "," 隔开(如:张三,李四,王五等)。当这些被添加的忽略用户给您发送短消息时将不予接收，如需禁止所有用户发来的短消息，请设置为 "{{ALL}}"',
	'pm_mark_unread' => '标记未读',

	'nopermission' => '您无权进行当前操作，这可能因以下原因之一造成:',
	'nopermission_no_loggedin' => '您还没有登录，请填写下面的登录表单后再尝试访问。',
	'nopermission_loggedin' => '您已经登录，但您的帐号或其所在的用户组无权访问当前页面。',

	'faq_usermaint' => '用户须知',

	'faq_usermaint_item1_q' => '我必须要注册吗？',
	'faq_usermaint_item2_q' => 'Discuz! 论坛使用 Cookies 吗？',
	'faq_usermaint_item3_q' => '如何使用签名？',
	'faq_usermaint_item4_q' => '如何使用个性化的头像？',
	'faq_usermaint_item5_q' => '如果我遗忘了密码，我该怎么办？',
	'faq_usermaint_item6_q' => '什么是“短消息”？',

	'faq_usermaint_item1_a' => '&nbsp; &nbsp; 这取决于管理员如何设置 Discuz! 论坛的用户组权限选项，您甚至有可能必须在注册成正式用户后后才能浏览帖子。当然，在通常情况下，您至少应该是正式用户才能发新帖和回复已有帖子。请 <a href="register.php">点击这里</a> 免费注册成为我们的新用户！<br><br>&nbsp; &nbsp; 强烈建议您注册，这样会得到很多以游客身份无法实现的功能。',
	'faq_usermaint_item2_a' => '&nbsp; &nbsp; Discuz! 采用 Session+Cookie 的双重方式保存用户信息，以确保在各种环境，包括 Cookie 完全无法使用的情况下您都能正常使用论坛各项功能。但 Cookies 的使用仍然可以为您带来一系列的方便和好处，因此我们强烈建议您在正常情况下不要禁止 Cookie 的应用，Discuz! 的安全设计将全力保证您的资料安全。<br><br>&nbsp; &nbsp; 在登录页面中，您可以选择 Cookie 记录时间，在该时间范围内您打开浏览器访问论坛将始终保持您上一次访问时的登录状态，而不必每次都输入密码。但出于安全考虑，如果您在公共计算机访问论坛，建议选择“浏览器进程”(默认)，或在离开公共计算机前选择“退出”(<a href="logging.php?action=logout">点击这里</a> 退出论坛)以杜绝资料被非法使用的可能。',
	'faq_usermaint_item3_a' => '&nbsp; &nbsp; 签名是加在您发表的帖子下面的小段文字，注册之后，您就可以设置自己的个性签名了。<br><br>&nbsp; &nbsp; <a href="memcp.php">点击这里</a> 进入控制面板，在签名框中输入签名文字，并确定不要超过管理员设置的相关限制(如字数、贴图等)，这样系统会自动选中您登录后发帖页面的显示签名选项，您的的签名将在帖子中自动被显示。',
	'faq_usermaint_item4_a' => '&nbsp; &nbsp; 同样在 <a href="memcp.php">控制面板</a> 中，有一处“头像”选项。头像是显示在您用户名下面的小图像，使用头像可能需要一定的权限，否则将不会显示出来。详情请查询<a href="faq.php?page=misc#3">本论坛的级别设定</a>，一般头像图像宽度应控制在 150 像素以下，以免影响界面美观。',
	'faq_usermaint_item5_a' => '&nbsp; &nbsp; Discuz! 提供发送取回密码链接到 Email 的服务，点击登录页面中的 <a href="member.php?action=lostpasswd">取回密码</a> 功能，可以为您把取回密码的方法发送到注册时填写的 Email 信箱中。如果您的 Email 已失效或无法收到信件，请与论坛管理员联系。',
	'faq_usermaint_item6_a' => '&nbsp; &nbsp; “短消息”是论坛注册用户间交流的工具，信息只有发件和收件人可以看到，收到信息后系统会出现铃声和相应提示，您可以通过短消息功能与同一论坛上的其他用户保持私人联系。<a href="pm.php" target="_blank">收件箱</a> 或 <a href="memcp.php">控制面板</a> 中提供了短消息的收发服务。',

	'faq_using' => '论坛使用',
	'faq_using_item1_q' => '在哪里可以登录？',
	'faq_using_item2_q' => '在哪里可以退出？',
	'faq_using_item3_q' => '我要搜索论坛，应该怎么做？',
	'faq_using_item4_q' => '怎样给其他人发送“短消息”？',
	'faq_using_item5_q' => '怎样看到全部的会员？',

	'faq_using_item1_a' => '&nbsp; &nbsp; 如果您尚未登录，点击左上角的“登录”，输入用户名和密码，确定即可。如果需要保持登录，请选择相应的 Cookie 时间，在此时间范围内您可以不必输入密码而保持上次的登录状态。',
	'faq_using_item2_a' => '&nbsp; &nbsp; 如果您已经登录，点击左上角的“退出”，系统会清除 Cookie，退出登录状态。',
	'faq_using_item3_a' => '&nbsp; &nbsp; 点击上面的 <a href="search.php">搜索</a>，输入搜索的关键字并选择一个范围，就可以检索到您有权限访问论坛中的相关的帖子。',
	'faq_using_item4_a' => '&nbsp; &nbsp; 如果您已登录，菜单上会显示出 <a href="pm.php" target="_blank">短消息</a>  项，点击后弹出短消息窗口，通过类似发送邮件一样的填写，点“发送”，消息就被发到对方收件箱中了。当他/她访问论坛的主要页面时，系统都会提示他/她收信息。',
	'faq_using_item5_a' => '&nbsp; &nbsp; 当管理员设置可用此项功能时，您可以通过点击 <a href="member.php?action=list">会员</a> 查看所有的会员及其资料，并可实现会员资料的检索和排序输出。',

	'faq_messages' => '读写帖子和收发短消息',
	'faq_messages_item1_q' => '如何发布新帖子？',
	'faq_messages_item2_q' => '如何回复帖子？',
	'faq_messages_item3_q' => '我能够删除主题吗？',
	'faq_messages_item4_q' => '怎样编辑自己发表的帖子？',
	'faq_messages_item5_q' => '我可不可以上传附件？',
	'faq_messages_item6_q' => '什么是 Smilies？',
	'faq_messages_item7_q' => '该怎样发起一个投票？',

	'faq_messages_item1_a' => '&nbsp; &nbsp; 在论坛版块中，点“发新帖”即可进入功能齐全的发帖界面。当然您也可以使用版块下面的“快速发帖”发表新帖(如果此选项打开)。注意，一般论坛都设置为需要登录后才能发帖。',
	'faq_messages_item2_a' => '&nbsp; &nbsp; 在浏览帖子时，点“回复帖子”即可进入功能齐全的回复界面。当然您也可以使用版块下面的“快速回复”发表回复(如果此选项打开)。注意，一般论坛都设置为需要登录后才能回复。',
	'faq_messages_item3_a' => '&nbsp; &nbsp; 浏览帖子时可以按下面的“编辑帖子”，对于您自己发表的帖子，可以很容易的编辑和删除。但当这帖是整个主题的起始帖时，则会删除该主题和全部回复。',
	'faq_messages_item4_a' => '&nbsp; &nbsp; 和上面一样，用“编辑帖子”就可以编辑自己发表的帖子。如果管理员通过论坛设置将这个功能屏蔽掉则不再可以进行此操作。',
	'faq_messages_item5_a' => '&nbsp; &nbsp; 可以。您可以在任何支持上传附件的版块中，通过发新帖、或者回复的方式上传附件（只要您的权限足够）。附件不能超过系统限定尺寸，且在可用类型的范围内才能上传。',
	'faq_messages_item6_a' => '&nbsp; &nbsp; Smilies 是一些用字符表示的表情符号，如果打开 Smilies 功能，Discuz! 会把一些符号转换成小图像，显示在帖子中，更加美观明了。目前支持下面这些 Smilies:<br>',
	'faq_messages_item7_a' => '&nbsp; &nbsp; 您可以像发帖一样在版块中发起投票。每行输入一个可能的选项（最多10个），您可以通过阅读这个投票帖选出自己的答案，每人只能投票一次，之后将不能再对您的选择做出更改。<br><br>&nbsp; &nbsp; 管理员拥有随时关闭和修改投票选项的权力。',
	'faq_messages_smilies_code' => '表情符号',
	'faq_messages_smilies_image' => '对应图像',

	'faq_misc' => '其他问题',
	'faq_misc_item1_q' => '能说明一下 Discuz! 代码的用法吗？',
	'faq_misc_item2_q' => '普通用户如何成为版主？',
	'faq_misc_item3_q' => '我如何在 $bbname 具有更多的权限？',

	'faq_misc_item1_a1' => '&nbsp; &nbsp; 您可以使用 Discuz! 代码--一个 HTML 代码的简化版本，来简化对帖子显示格式的控制。<br><br>
<ol type="1">
<li>[b]粗体文字 Abc[/b] &nbsp; 效果:<b>粗体文字 Abc</b> （粗体字）<br><br></li>
<li>[i]斜体文字 Abc[/i] &nbsp; 效果:<i>斜体文字 Abc</i> （斜体字）<br><br></li>
<li>[u]下划线文字 Abc[/u] &nbsp; 效果:<u>下划线文字 Abc</u> （下划线）<br><br></li>
<li>[color=red]红颜色[/color] &nbsp; 效果:<font color="red">红颜色</font> （改变文字颜色）<br><br></li>
<li>[size=3]文字大小为 3[/size] &nbsp; 效果:<font size="3">文字大小为 3</font> （改变文字大小）<br><br></li>
<li>[font=仿宋]字体为仿宋[/font] &nbsp; 效果:<font face"仿宋">字体为仿宋</font> （改变字体）<br><br></li>
<li>[align=Center]内容居中[/align] &nbsp; （格式内容位置） 效果:<br><center>内容居中</center><br></li>
<li>[url]http://www.comsenz.com[/url] &nbsp; 效果:<a href="http://www.comsenz.com" target="_blank">http://www.comsenz.com</a> （超级连接）<br><br></li>
<li>[url=http://www.Discuz.net]Discuz! 论坛[/url] &nbsp; 效果:<a href="http://www.Discuz.net" target="_blank">Discuz! 论坛</a> （超级连接）<br><br></li>
<li>[email]myname@mydomain.com[/email] &nbsp; 效果:<a href="mailto:myname@mydomain.com">myname@mydomain.com</a> （E-Mail 链接）<br><br></li>
<li>[email=support@discuz.net]Discuz! 技术支持[/email] &nbsp; 效果:<a href="mailto:support@discuz.net">Discuz! 技术支持</a> （E-Mail 链接）<br><br></li>
<li>[quote]Discuz! Board 是由北京康盛世纪科技有限公司开发的论坛软件[/quote] &nbsp; （引用内容，类似的代码还有 [code][/code]）<br><br></li>
<li>[hide]免费帐号为: username/password[/hide] &nbsp; （按回复隐藏内容，仅限版主及管理员使用）<br>效果:只有当浏览者回复本帖时，才显示其中的内容，否则显示为“<b>**** 隐藏信息 跟帖后才能显示 *****</b>”<br><br></li>
<li>[hide=20]免费帐号为: username/password[/hide] &nbsp; （按积分隐藏内容，仅限版主及管理员使用）<br>效果:只有当浏览者积分高于 20 点时，才显示其中的内容，否则显示为“<b>**** 隐藏信息 积分高于 20 点才能显示 ****</b>”<br><br></li>
<li>[list]<br>
[*]列表项 #1<br>
[*]列表项 #2<br>
[*]列表项 #3<br>
[/list] &nbsp; (列表)<br><br></li>',
	'faq_misc_item1_a2' => '<br>以下 Discuz! 代码需论坛可用 [img] 代码才能使用<hr noshade size="0" width="50%" color="{BORDERCOLOR}" align="left"><br>
<li>[img]{$boardurl}images/default/logo.gif[/img] &nbsp; （链接图像）<br>效果:<br><img src="images/default/logo.gif"> <br><br></li>
<li>[img=88,31]{$boardurl}images/logo.gif[/img] &nbsp;（链接图像并限制大小）<br> 效果:<br><img src="images/logo.gif" height="31" width="88"> <br><br></li>
<li>[swf]{$boardurl}images/banner.swf[/swf] &nbsp; （链接 flash 动画，用法与 [img] 类似）<br><br></li>
</ol>',
	'faq_misc_item2_a' => '&nbsp; &nbsp; 论坛的版主是自愿申请的，管理员可能会要求版主需要达到一定积分，或在论坛注册超过一定时间等。版主应该是诚实守信、乐于助人、大公无私的表率，同时还要熟悉专业，经验丰富，有良好的口碑。如果你确认已经达到上面几点，并希望担任本站的版主，可以与管理员联系。',
	'faq_misc_item3_a' => '&nbsp; &nbsp; 本站所使用的 Discuz! 论坛是按照系统头衔和用户积分区分的，积分可以参考您的发帖量，其他用户的评分，或两者综合来决定。
当积分达到一定等级要求时，系统会自动为您开通新的权限，并给予相应星星标志。因此，拥有较高的积分数，不仅代表您在本论坛的资历与活跃程度，同时也意味着能够拥有比其他
用户更多的高级权限。'
);

?>